name: Release Homebrew

on:
  workflow_call:
  workflow_dispatch:
    input:
      notUsed:
        type: string
        description: Run this workflow from a "release-*" branch. This input does nothing.
        required: false

jobs:
  release-homebrew:
    runs-on: ubuntu-latest
    environment: ReleaseHomebrew
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Install AWS cli
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli
      - name: yarn install
        run: |
          cp yarn.lock apps/cli
          cd apps/cli
          yarn --frozen-lockfile --network-timeout 1000000
      - run: echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
      - name: release homebrew
        run: ./scripts/homebrew/homebrew.mjs
        env:
          GITHUB_SHA_SHORT: ${{ env.GITHUB_SHA_SHORT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_EC2_METADATA_DISABLED: true
